name: integration tests

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft]

jobs:
  integration-test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rebase
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/create-k3d-cluster
      - name: run test
        run: make -C hack/ci integration-test-on-cluster
        env:
          IMG: europe-docker.pkg.dev/kyma-project/dev/keda-manager:PR-${{ github.event.number }}
