name: keda verify

on:
  push:
    branches: [ "main", "release-*" ]
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - converted_to_draft

jobs:
  # pre-keda-manager-operator-lint
  lint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rebase
      - uses: ./.github/actions/setup-go
      - uses: golangci/golangci-lint-action@v4.0.0
        with:
          version: latest
          working-directory: '.'
  # pre-keda-manager-operator-tests
  unit-test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rebase
      - uses: ./.github/actions/setup-go
      - name: run test
        run: make test
  
  # pre-keda-manager-verify
  integration-test:
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rebase
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/create-single-cluster
      - name: run test
        run: make -C hack/ci integration-test-on-cluster
        env:
          IMG: europe-docker.pkg.dev/kyma-project/dev/keda-manager:PR-${{ github.event.number }}
  # post-keda-manager-upgrade-latest-to-main
  upgrade-test:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/create-single-cluster
      - name: run test
        run: make -C hack/ci upgrade-test
        env:
          IMG: europe-docker.pkg.dev/kyma-project/prod/keda-manager:${{ github.sha }}
